### ISSUE TITLE
Is the describe-genome.py --features argument broken?

### ISSUE THREAD

**Issue by imLew** [VirologyCharite/gb2seq#4]
When I try to use this argument with e.g. `CDS` as value I get a key error because `Features.__getitem__` tries to look up the name of the feature in a dict that seem to always be empty.

Here is the error , where I installed gb2seq from master with `pip install -e .` and added a print statement for the `aliasDict`.
```
$ describe-genome.py --genome genbank-files/NC_001806.fasta --ref genbank-files/NC_001806.gb --feature CDS --printNtSeq --outDir genbank-files/NC_001806-proteins                                                      [10:46:12]
/home/nikolai/Software/mambaforge/envs/diamond-misses/bin/describe-genome.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('gb2seq==0.2.20')
{}
Traceback (most recent call last):
  File "/home/nikolai/Software/mambaforge/envs/diamond-misses/bin/describe-genome.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/nikolai/Work/diamond_misses/gb2seq/bin/describe-genome.py", line 498, in <module>
    sys.exit(main(args))
  File "/home/nikolai/Work/diamond_misses/gb2seq/bin/describe-genome.py", line 320, in main
    processFeature(featureName, alignment, fps, i, args)
  File "/home/nikolai/Work/diamond_misses/gb2seq/bin/describe-genome.py", line 192, in processFeature
    referenceNt, genomeNt = genome.ntSequences(featureName)
  File "/home/nikolai/Work/diamond_misses/gb2seq/gb2seq/alignment.py", line 308, in ntSequences
    feature = self.features[featureName]
  File "/home/nikolai/Work/diamond_misses/gb2seq/gb2seq/features.py", line 416, in __getitem__
    return self.data[self.canonicalName(name)]
  File "/home/nikolai/Work/diamond_misses/gb2seq/gb2seq/features.py", line 437, in canonicalName
    raise KeyError(name)
KeyError: 'CDS'
```

I think the problem is that `Features` requires an `aliases:dict` argument if `sars2==False`, but when `describe-genome.py` creates the instance that argument is not given.
https://github.com/VirologyCharite/gb2seq/blob/85d2e7d5109431df896904625084fa123847e3ee/bin/describe-genome.py#L264.

**Comment by terrycojones** [comment]
I will have a look, thanks. The `--feature` option is supposed to take a feature name (probably it should be called `--featureName`).  Try `describe-feature.py --names` to see them.  In any case, the above should produce a nice error, not an exception.

**Comment by imLew** [comment]
I thought it would take a kind of genbank feature, i.e. something from this list https://emunix.emich.edu/~mevett/BioinformaticsTools/GenBank_features.htm

It does work when I use one of the features returned by `describe-feature.py --names` (it doesn't seem to call the `canonicalNames` function when in that case).
